"""
OTel-compatible correlation/trace context (ch18 "Telemetry", pure domain).

A :class:`CorrelationContext` carries the request correlation id plus an optional
W3C ``traceparent`` trace/span id. It is bound to the executing task via
``contextvars`` so structured logs, metric samples and durable job/event metadata
share one identity without threading it through every signature.

Inbound identifiers are validated before use: an unparseable ``traceparent`` or an
out-of-charset correlation id is dropped (a fresh one is generated by the caller),
so arbitrary attacker-controlled header bytes are never reflected into logs or
responses. Only stdlib is used (domain stays framework-free).
"""

from __future__ import annotations

import os
import re
import uuid
from collections.abc import Callable
from contextvars import ContextVar, Token
from dataclasses import dataclass

# Bounded correlation-id charset: short, log-safe, no whitespace/UTF-8/control bytes.
_REQUEST_ID_RE = re.compile(r"^[A-Za-z0-9._-]{1,128}$")

_HEX = set("0123456789abcdef")

# W3C traceparent layout: <2-hex version>-<32-hex trace>-<16-hex span>-<2-hex flags>.
_TRACEPARENT_PARTS = 4
_HEX_PAIR_LEN = 2


def _is_hex(value: str, length: int) -> bool:
    """Return True when ``value`` is exactly ``length`` lowercase hex chars, not all-zero."""
    # W3C forbids only the all-zero id; a repeated non-zero char (e.g. 'f' * 32) is valid.
    return len(value) == length and all(c in _HEX for c in value) and value != "0" * length


@dataclass(frozen=True, slots=True)
class TraceContext:
    """A parsed W3C ``traceparent`` (version 00) trace identity."""

    trace_id: str
    span_id: str
    trace_flags: str


@dataclass(frozen=True, slots=True)
class CorrelationContext:
    """One request's correlation + optional trace identity (immutable)."""

    request_id: str
    trace_id: str | None = None
    span_id: str | None = None
    trace_flags: str | None = None


def is_valid_request_id(value: str) -> bool:
    """Return True when the correlation id is in the bounded, log-safe charset."""
    return _REQUEST_ID_RE.fullmatch(value) is not None


def new_request_id() -> str:
    """Mint a fresh, bounded correlation id (128-bit, hex)."""
    return uuid.uuid4().hex


def new_trace_id() -> str:
    """Mint a fresh 128-bit trace id (32 hex chars)."""
    return os.urandom(16).hex()


def new_span_id() -> str:
    """Mint a fresh 64-bit span id (16 hex chars)."""
    return os.urandom(8).hex()


def parse_traceparent(value: str) -> TraceContext | None:
    """
    Parse a W3C ``traceparent`` (``00-<32hex>-<16hex>-<2hex>``).

    Returns None (never raises) for any malformed, non-zero-padded, all-zero or
    out-of-range value, so callers can fall back to a generated trace.
    """
    parts = value.strip().split("-")
    if len(parts) != _TRACEPARENT_PARTS:
        return None
    version, trace_id, span_id, flags = parts
    if len(version) != _HEX_PAIR_LEN or not all(c in _HEX for c in version) or version == "ff":
        return None
    if not _is_hex(trace_id, 32) or not _is_hex(span_id, 16):
        return None
    if len(flags) != _HEX_PAIR_LEN or not all(c in _HEX for c in flags):
        return None
    return TraceContext(trace_id=trace_id, span_id=span_id, trace_flags=flags)


def format_traceparent(trace_id: str, span_id: str, trace_flags: str = "01") -> str:
    """Render a W3C ``traceparent`` string (version 00, sampled flag by default)."""
    return f"00-{trace_id}-{span_id}-{trace_flags}"


def context_from_request(
    *, request_id: str | None, traceparent: str | None
) -> CorrelationContext:
    """
    Build a validated context from inbound headers.

    An invalid ``request_id`` is replaced with a fresh one; an invalid/absent
    ``traceparent`` yields a context with no trace identity (the caller may start
    a new trace separately). Never reflects unvalidated header bytes.
    """
    if request_id is not None and is_valid_request_id(request_id):
        valid_request_id: str = request_id
    else:
        valid_request_id = new_request_id()
    parsed = parse_traceparent(traceparent) if traceparent is not None else None
    if parsed is None:
        return CorrelationContext(request_id=valid_request_id)
    return CorrelationContext(
        request_id=valid_request_id,
        trace_id=parsed.trace_id,
        span_id=parsed.span_id,
        trace_flags=parsed.trace_flags,
    )


_context_var: ContextVar[CorrelationContext | None] = ContextVar(
    "milpbooklm_correlation", default=None
)


def current_context() -> CorrelationContext | None:
    """Return the context bound to the current task, or None."""
    return _context_var.get()


def bind_context(ctx: CorrelationContext) -> Token[CorrelationContext | None]:
    """Bind ``ctx`` to the current task; returns the token for :func:`reset_context`."""
    return _context_var.set(ctx)


def reset_context(token: Token[CorrelationContext | None]) -> None:
    """Restore the context to its pre-bind state (always call in a ``finally``)."""
    _context_var.reset(token)


def run_with_context[T](ctx: CorrelationContext, fn: Callable[[], T]) -> T:
    """Run ``fn`` with ``ctx`` bound, resetting the context in a ``finally``."""
    token = bind_context(ctx)
    try:
        return fn()
    finally:
        reset_context(token)
