from collections.abc import Iterator, Mapping

class EpubException(Exception): ...  # noqa: N818 - third-party API name

class EpubItem:
    def get_name(self) -> str: ...
    def get_content(self) -> bytes: ...

class EpubBook:
    def get_items_of_type(self, item_type: int) -> Iterator[EpubItem]: ...

def read_epub(name: str, options: Mapping[str, bool] | None = None) -> EpubBook: ...
