"""
Shared column builders for the ch05 schema (FND-03).

TECH-05-001: uuid primary keys with PostgreSQL 18 ``uuidv7()`` database defaults
(TAD-011: ordered ids are generated by the database, never in Python) and UTC
``timestamptz`` timestamps. Mutable roots additionally carry an integer
``revision`` and an ``etag`` (If-Match) column for compare-and-swap updates.
"""

from __future__ import annotations

from typing import Any

import sqlalchemy as sa

# Single MetaData for the whole ch05 schema: the alembic baseline creates/drops all of it,
# and metadata.create_all orders tables by foreign-key dependency.
METADATA = sa.MetaData()

UUID_PK_DEFAULT = sa.text("uuidv7()")


def uuid_pk(name: str = "id") -> sa.Column[Any]:
    """Provide a uuid primary key defaulting to the database-side uuidv7() (TAD-011)."""
    return sa.Column(name, sa.Uuid(as_uuid=True), primary_key=True, server_default=UUID_PK_DEFAULT)


def uuid_fk(
    name: str,
    table: str,
    *,
    nullable: bool = False,
    ondelete: str = "RESTRICT",
) -> sa.Column[Any]:
    """Provide a uuid foreign key column into an existing table."""
    return sa.Column(
        name,
        sa.Uuid(as_uuid=True),
        sa.ForeignKey(f"{table}.id", ondelete=ondelete),
        nullable=nullable,
    )


def created_at() -> sa.Column[Any]:
    """UTC creation timestamp, database-defaulted."""
    return sa.Column(
        "created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
    )


def updated_at() -> sa.Column[Any]:
    """UTC last-update timestamp, database-defaulted."""
    return sa.Column(
        "updated_at",
        sa.DateTime(timezone=True),
        nullable=False,
        server_default=sa.func.now(),
        onupdate=sa.func.now(),
    )


def revision_column() -> sa.Column[Any]:
    """Integer optimistic-concurrency revision (If-Match CAS), per TECH-05-001."""
    return sa.Column("revision", sa.Integer, nullable=False, server_default=sa.text("0"))


def etag_column() -> sa.Column[Any]:
    """ETag/If-Match carrier paired with ``revision`` (TECH-05-001)."""
    return sa.Column("etag", sa.Text, nullable=False, server_default=sa.text("'0'"))


def content_sha256(name: str = "content_sha256") -> sa.Column[Any]:
    """SHA-256 hex digest of immutable content."""
    return sa.Column(name, sa.Text, nullable=False)
